### ISSUE TITLE
Active Contribution Request

### ISSUE THREAD

**Issue by hmert** [jbouzekri/FileUploaderBundle#11]
@jbouzekri Hi, we want to contribute your project actively.

All of these PR's are ours. We're so proud to be as a part of the project.
https://github.com/jbouzekri/FileUploaderBundle/pulls?utf8=%E2%9C%93&q=is%3Apr+

We've already been maintaining https://github.com/APY/, https://github.com/ojs and https://github.com/okulbilisim as well.

I offer you that to maintain the project on a organization (new or our).

Thank you.

**Comment by delirehberi** [comment]
+1

**Comment by behram** [comment]
:+1:

**Comment by jbouzekri** [comment]
Hi,
Sorry I was on holiday and unavailable.
I would be glad to open my bundle to any new contributors. 
@hmert I have given you push rights. So you should be able to handle the pull requests.
Please tell me if this is enough or not.
Regards

**Comment by hmert** [comment]
Hi @jbouzekri,
Thank you! It's okay for now.

Please consider to migrate this bundle to an organization.
