### ISSUE TITLE
JS Library Update

### ISSUE THREAD

**Issue by hmert** [jbouzekri/FileUploaderBundle#13]
Hi everyone,

We should update the js libs. There are many bugfixes/features that we have not yet.

https://github.com/jbouzekri/FileUploaderBundle/tree/master/Resources/public/lib

/cc @jbouzekri

**Comment by jbouzekri** [comment]
Hi,

Yes it would be good.

I added the library directly in the bundle because at that time not everybody was using tools like bower or npm and I did not want to force it but maybe we should consider this.

Or maybe using the submodules ...

**Comment by hmert** [comment]
submodules :-1: 

we should use `bower` with compatible version of library.

I'll assign this issue to me and create a branch. 

Is it OK for you?

**Comment by jbouzekri** [comment]
Happy new year.

Ok for the branch.
