### ISSUE TITLE
How to get image web path.

### ISSUE THREAD

**Issue by anacona16** [jbouzekri/FileUploaderBundle#18]
Hi, I implemented the bundle and is working now, my question is, how to get the web url to show the image on a twig template?

**Comment by jbouzekri** [comment]
Hi @anacona16 this bundle is just a linker between OneupUploaderBundle, KnpGaufretteBundle and LiipImagineBundle

OneupUploaderBundle : manage upload of image with ajax
KnpGaufretteBundle : manage image storage
LiipImagineBundle : manage image processing

So you can use liip twig filter to display your image.

Something like that : 

``` twig
<img src="{{ myentity.image_field | imagine_filter('my_liip_filter') }}" />
```

Note that your liip filter should use the right data_loader which matches the configuration you used for the oneup and knp bundles
