### ISSUE TITLE
Depreciated OptionsResolverInterface still being used

### ISSUE THREAD

**Issue by bluntelk** [jbouzekri/FileUploaderBundle#20]
Hi There,

I was trying to use the Image Validator functionality and it was giving an error 500.

I traced it back to an interface that was depreciated and removed in v3.0 of symfony

classes Affected
* Jb\Bundle\FileUploaderBundle\Service\Validator\AbstractImageValidator
* Jb\Bundle\FileUploaderBundle\Service\Validator\AbstractValidator

I have a pull request coming that solves these problems

**Comment by jbouzekri** [comment]
@bluntelk I must confess that I did not test validator again when this bundle moved to sf3. Sorry for that. Thanks for the fix. I have tagged a new 4.1 version.
