### ISSUE TITLE
Multiple images

### ISSUE THREAD

**Issue by lumilo8** [jbouzekri/FileUploaderBundle#3]
Hi, is it possible upload multiple files?

**Comment by jbouzekri** [comment]
No, for now, it is not possible out of the box.

The only solution I can think of when using my bundle is to have a collection field with a oneToMany relation to an entity storing the image. You could then make a form with a collection (allow_add and allow_delete). It would not be a multiple upload in the same click but it will allow you to provide features like image gallery, ...
